import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '../globals.css'

const montSerrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Serviços',
  description: 'Generated by create next app',
}

export default function ServicesLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montSerrat.className} overflow-x-hidden`}>
        {children}
      </body>
    </html>
  )
}
